# agent4_dashboard/agent4.py
# Agent 4: PDF Violation Report Generator
#
# Split by design:
#   - Per-violation FACTS (timestamp, duration, zone, VLM verdict) are laid
#     out in a plain ReportLab table, straight from the DB. Deterministic,
#     no hallucination risk - a template does this more reliably than an LLM.
#   - The NARRATIVE paragraph per person is generated by a text LLM that
#     looks ACROSS all of that person's violations for patterns a template
#     can't surface (recurring zones, timing clusters, escalation across the
#     session) - not restating individual lines, which would be redundant
#     with the table above it.
#
# NARRATIVE_MODEL is a plain text-instruct model via Ollama - NOT the same
# model as agent3's LLaVA (that one's vision-only, used for frame auditing).

import os
import sys
import sqlite3
from datetime import datetime

import ollama
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(ROOT_DIR)
from config import DATABASE_PATH

REPORT_PATH = os.path.join(ROOT_DIR, "report.pdf")

# Chosen for proven summarization reliability over novelty - runs on CPU
# (slow, but fine for a one-shot end-of-session report) and auto-uses GPU
# whenever available with no code change.
NARRATIVE_MODEL = "llama3.1:8b"

print("\n=== AGENT 4 STARTING: REPORT GENERATION ===")


def fetch_violations():
    """
    Returns (people, general) where:
      people:  dict of {person_id (int) -> [violation dicts]} for violations
               tied to a specific tracked identity.
      general: list of violation dicts for rows with person_id IS NULL - e.g.
               a whole-room/whole-frame violation (like "everyone AFK") that
               was never scoped to one person in the first place. These are
               NOT a "Person None" - they're a separate category entirely, so
               they're kept out of `people` from the start rather than being
               grouped under a None key (which is also what crashed
               sorted(people.keys()) below: None and str/int can't be
               compared in Python 3, and it was semantically wrong besides -
               a person_id of NULL was never actually "a person").
    """
    conn = sqlite3.connect(DATABASE_PATH)
    rows = conn.execute("""
        SELECT person_id, event_type, timestamp, duration_seconds,
               zone_id, zone_name, vlm_summary
        FROM events
        WHERE event_type LIKE 'violation_%'
        ORDER BY person_id, timestamp
    """).fetchall()
    conn.close()

    people = {}
    general = []
    for pid, etype, ts, duration, zone_id, zone_name, vlm in rows:
        entry = {
            "type": etype.replace("violation_", "").replace("_", " ").upper(),
            "timestamp": ts or 0.0,
            "duration": duration or 0.0,
            "zone_name": zone_name,
            "vlm": vlm or "\u2014",
        }
        # pid is None: legacy rows written before the migration/sentinel fix.
        # pid == 0: the reserved "general/whole-room" sentinel going forward.
        # Either way, it's not a real tracked person - route to `general`.
        if pid is None or pid == 0:
            general.append(entry)
        else:
            people.setdefault(pid, []).append(entry)
    return people, general


def generate_narrative(person_id, violations):
    """One short paragraph synthesizing patterns across this person's
    violations. Deliberately NOT used to restate individual facts - those
    stay in the deterministic table. Falls back to a plain notice (not a
    fabricated summary) if the Ollama call fails, so a model outage never
    silently produces misleading report content."""
    lines = []
    for v in violations:
        mins = v["timestamp"] / 60
        lines.append(
            f"- {v['type']} at {mins:.1f} min, lasted {v['duration']:.0f}s, "
            f"zone={v['zone_name'] or 'N/A'}, VLM verdict={v['vlm']}"
        )
    violation_block = "\n".join(lines)

    prompt = (
        "You are writing one short paragraph (3-5 sentences) for a workplace "
        "surveillance audit report. Summarize behavioral PATTERNS across this "
        "person's violations below - do not restate each line individually. "
        "Note any recurring zones, timing clusters, or escalation across the "
        "session. Be factual and neutral - do not speculate about intent, "
        "cause, or the person's state of mind, and do not invent any numbers "
        "not present below.\n\n"
        f"Person {person_id} violations:\n{violation_block}\n\n"
        "Paragraph:"
    )

    try:
        response = ollama.chat(
            model=NARRATIVE_MODEL,
            messages=[{"role": "user", "content": prompt}],
        )
        return response["message"]["content"].strip()
    except Exception as e:
        print(f"  [Agent4 WARNING] LLM narrative failed for Person {person_id}: {e}")
        return ("Narrative summary unavailable (LLM call failed) - "
                "see the table above for the full deterministic violation record.")


def build_violation_table(violations):
    """Shared table-building logic for both a person's section and the
    general (unattributed) section below."""
    table_data = [["Type", "Time", "Duration", "Zone", "VLM Verdict"]]
    for v in violations:
        mins = v["timestamp"] / 60
        table_data.append([
            v["type"], f"{mins:.1f} min", f"{v['duration']:.0f}s",
            v["zone_name"] or "\u2014", v["vlm"],
        ])

    tbl = Table(table_data, colWidths=[1.3*inch, 0.9*inch, 0.9*inch, 1.2*inch, 1.6*inch])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e1b4b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return tbl


def build_pdf(people, general):
    doc = SimpleDocTemplate(
        REPORT_PATH, pagesize=letter,
        topMargin=0.6 * inch, bottomMargin=0.6 * inch,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
    )
    styles = getSampleStyleSheet()
    body_style = ParagraphStyle("body", parent=styles["BodyText"], fontSize=10, leading=14)
    narrative_style = ParagraphStyle(
        "narrative", parent=styles["BodyText"], fontSize=10, leading=14,
        textColor=colors.HexColor("#334155"), spaceBefore=6, spaceAfter=14,
        leftIndent=8, borderLeftWidth=2, borderLeftColor=colors.HexColor("#6366f1"),
        borderPadding=8, backColor=colors.HexColor("#f8fafc"),
    )

    story = [
        Paragraph("Smart Surveillance System \u2014 Violation Report", styles["Title"]),
        Paragraph(f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}", body_style),
        Spacer(1, 0.25 * inch),
    ]

    if not people and not general:
        story.append(Paragraph("No violations were recorded for this session.", body_style))
    else:
        # Per-person sections first, sorted by person_id - safe now since
        # `people` only ever contains real (non-None) person_ids.
        for pid in sorted(people.keys()):
            violations = people[pid]
            story.append(Paragraph(f"Person {pid}", styles["Heading2"]))
            story.append(build_violation_table(violations))
            story.append(Spacer(1, 0.15 * inch))

            print(f"[INFO] Generating narrative for Person {pid} ({len(violations)} violation(s))...")
            narrative = generate_narrative(pid, violations)
            story.append(Paragraph(f"<b>Summary:</b> {narrative}", narrative_style))

        # General/unattributed violations - things like a whole-room "everyone
        # AFK" event that was never tied to one tracked identity. Shown as
        # its own section rather than under any "Person" heading, and with
        # no per-person narrative (there's no single person's pattern to
        # summarize here).
        if general:
            story.append(Paragraph("General Violations (not tied to a specific person)", styles["Heading2"]))
            story.append(build_violation_table(general))
            story.append(Spacer(1, 0.15 * inch))

    doc.build(story)


def main():
    people, general = fetch_violations()
    total_people = len(people)
    print(f"[INFO] {total_people} person(s) with violations found.")
    if general:
        print(f"[INFO] {len(general)} general (unattributed) violation(s) found.")
    build_pdf(people, general)
    print(f"[SUCCESS] Report saved to {REPORT_PATH}")
    print("\n########################################")
    print("  AGENT 4 COMPLETE: REPORT GENERATED")
    print("########################################")


if __name__ == "__main__":
    main()